# Generated by Django 5.1.4 on 2025-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantty',
            new_name='quantity',
        ),
    ]
